### ISSUE TITLE
Investigate how to register new runner

### ISSUE THREAD

**Issue by LinuxBozo** [CMSgov/github-actions-runner-aws#1]
In order to use an internal runner, you have to register that runner with GitHub. This is a story to investigate and document how we can do this within the confines of CMS (can we register at the org level? Does it have to be repository level?)

Acceptance: We have documentation around how to do this properly
 

https://docs.github.com/en/actions/hosting-your-own-runners/adding-self-hosted-runners

**Comment by lxuo-trussworks** [comment]
Here's a summary of the important points via researching the existing docs. It'd be good to pair with someone to confirm some of the different options/limitations for the CMS environment, since that'll dictate which routes are open to us for implementation:

[Adding self-hosted runners](https://docs.github.com/en/actions/hosting-your-own-runners/adding-self-hosted-runners)

- Runners can be added at the repository level
  - Only works for the specific repository in question
  - You must be the repository owner. For an organization repository, you must be an organization owner or have admin access to the repository.
- Runners can be added at the organization level
  - Can be used by any repository within the organization
  - Will be used to process jobs for multiple repositories
  - To add a self-hosted runner to an organization, you must be an organization owner.
- Security considerations
  - Self-hosted runners should only be used with private repositories - public repositories could have malicious code executed on the runners by third parties
    - Not a concern with Github hosted runners because they isolate and destroy-after-use each runner they host
- Network communication considerations
  - Runners have to communicate with Github, so they need appropriate network access to a specific list of URLs (see list below)
  - If IP address allow lists is used for the Github organization, the self-hosted runner’s IP address must be added to the allow list
  - It’s possible to use a self-hosted runner via a proxy server
    - It requires setting specific environment variables
    - The environment variables must be set before configuring or starting the self-hosted runner application. If your proxy configuration changes, you must restart the self-hosted runner application.
    - You can also set the environment variables within a .env file
    - Docker container actions or service containers might require additional configuration for Docker to use the proxy server

**Runners URL List**
```
github.com
api.github.com
*.actions.githubusercontent.com
github-releases.githubusercontent.com
github-registry-files.githubusercontent.com
codeload.github.com
*.pkg.github.com
pkg-cache.githubusercontent.com
pkg-containers.githubusercontent.com
pkg-containers-az.githubusercontent.com
```

**Comment by LinuxBozo** [comment]
Ok, for now then, it seems that a per repo basis for all this appears to be the best path forward in terms of permissions, access, and trying to limit this to private repos.

**Comment by LinuxBozo** [comment]
Let's write up this in an ADR. https://confluenceent.cms.gov/pages/viewpage.action?pageId=177345029

**Comment by lxuo-trussworks** [comment]
Another question that comes to mind... do we have any inclination as to whether we'd need to use a proxy server or not? And maybe "don't know yet", but was just wondering if that should be in this ADR or a separate ADR.

**Comment by LinuxBozo** [comment]
We should have direct access to GitHub via egress from AWS, so no proxy required.

**Comment by lxuo-trussworks** [comment]
Cool, thanks!

**Comment by lxuo-trussworks** [comment]
Here's an ADR around the repo vs org level management:
https://confluenceent.cms.gov/display/CMCSMAC/0006+-+Repo+vs.+org+level+self-hosted+Github+Action+runners
